-- 1. Drop ALL Foreign Key Constraints that might interfere
ALTER TABLE "public"."conversations" DROP CONSTRAINT IF EXISTS "conversations_user_id_fkey";
ALTER TABLE "public"."comments" DROP CONSTRAINT IF EXISTS "comments_conversation_id_fkey";
ALTER TABLE "public"."comments" DROP CONSTRAINT IF EXISTS "comments_user_id_fkey";
ALTER TABLE "public"."conversation_skills" DROP CONSTRAINT IF EXISTS "conversation_skills_conversation_id_fkey";
ALTER TABLE "public"."conversation_skills" DROP CONSTRAINT IF EXISTS "conversation_skills_skill_id_fkey";
ALTER TABLE "public"."environments" DROP CONSTRAINT IF EXISTS "environments_conversation_id_fkey";
ALTER TABLE "public"."skills" DROP CONSTRAINT IF EXISTS "skills_user_id_fkey";

-- Also drop constraints for other likely tables mentioned in entities
DO $$ 
BEGIN 
    -- On-chain transactions
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'on_chain_transactions_conversation_id_fkey') THEN
        ALTER TABLE "public"."on_chain_transactions" DROP CONSTRAINT "on_chain_transactions_conversation_id_fkey";
    END IF;
    -- Messages
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'messages_conversation_id_fkey') THEN
        ALTER TABLE "public"."messages" DROP CONSTRAINT "messages_conversation_id_fkey";
    END IF;
    -- Interactions
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'interactions_conversation_id_fkey') THEN
        ALTER TABLE "public"."interactions" DROP CONSTRAINT "interactions_conversation_id_fkey";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'interactions_user_id_fkey') THEN
        ALTER TABLE "public"."interactions" DROP CONSTRAINT "interactions_user_id_fkey";
    END IF;
    -- Unlocks
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unlocks_conversation_id_fkey') THEN
        ALTER TABLE "public"."unlocks" DROP CONSTRAINT "unlocks_conversation_id_fkey";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unlocks_user_id_fkey') THEN
        ALTER TABLE "public"."unlocks" DROP CONSTRAINT "unlocks_user_id_fkey";
    END IF;
    -- Follows
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'follows_follower_id_fkey') THEN
        ALTER TABLE "public"."follows" DROP CONSTRAINT "follows_follower_id_fkey";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'follows_following_id_fkey') THEN
        ALTER TABLE "public"."follows" DROP CONSTRAINT "follows_following_id_fkey";
    END IF;
END $$;

-- 2. Fix Users table
ALTER TABLE "public"."users" ALTER COLUMN "id" TYPE bigint USING (id::bigint);
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = '"public"."users"'::regclass AND attname = 'id' AND attidentity != '') THEN
        ALTER TABLE "public"."users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "updated_at" timestamp(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "email" text;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "password_hash" text;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "api_key" text;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "avatar" text;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "bio" text;
ALTER TABLE "public"."users" ADD COLUMN IF NOT EXISTS "user_type" text;
ALTER TABLE "public"."users" ALTER COLUMN "created_at" TYPE timestamp(3) WITH TIME ZONE USING (created_at AT TIME ZONE 'UTC');

-- 3. Fix Conversations table
ALTER TABLE "public"."conversations" ALTER COLUMN "id" TYPE bigint USING (id::bigint);
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = '"public"."conversations"'::regclass AND attname = 'id' AND attidentity != '') THEN
        ALTER TABLE "public"."conversations" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
ALTER TABLE "public"."conversations" ALTER COLUMN "user_id" TYPE bigint USING (user_id::bigint);
ALTER TABLE "public"."conversations" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "public"."conversations" ALTER COLUMN "price" TYPE numeric USING (price::numeric);
ALTER TABLE "public"."conversations" ALTER COLUMN "price" DROP NOT NULL;
ALTER TABLE "public"."conversations" ADD COLUMN IF NOT EXISTS "updated_at" timestamp(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "public"."conversations" ALTER COLUMN "created_at" TYPE timestamp(3) WITH TIME ZONE USING (created_at AT TIME ZONE 'UTC');

-- Allow nulls for legacy fields
ALTER TABLE "public"."conversations" ALTER COLUMN "title" DROP NOT NULL;
ALTER TABLE "public"."conversations" ALTER COLUMN "raw_content" DROP NOT NULL;
ALTER TABLE "public"."conversations" ALTER COLUMN "source_type" DROP NOT NULL;
ALTER TABLE "public"."conversations" ALTER COLUMN "is_public" DROP NOT NULL;

ALTER TABLE "public"."conversations" 
  ADD COLUMN IF NOT EXISTS "resume_id" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "owner_id" bigint,
  ADD COLUMN IF NOT EXISTS "owner_wallet" text,
  ADD COLUMN IF NOT EXISTS "blob_id" text,
  ADD COLUMN IF NOT EXISTS "encryption_key" text,
  ADD COLUMN IF NOT EXISTS "encryption_id" text,
  ADD COLUMN IF NOT EXISTS "policy_object_id" text,
  ADD COLUMN IF NOT EXISTS "encryption_type" text,
  ADD COLUMN IF NOT EXISTS "encryption_mode" text,
  ADD COLUMN IF NOT EXISTS "summary" jsonb,
  ADD COLUMN IF NOT EXISTS "unlock_count" int4,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "ipfs_cid" text;

-- 4. Fix Referencing Columns
ALTER TABLE "public"."comments" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);
ALTER TABLE "public"."comments" ALTER COLUMN "user_id" TYPE bigint USING (user_id::bigint);
ALTER TABLE "public"."conversation_skills" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);
ALTER TABLE "public"."environments" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);

DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'skills') THEN
        ALTER TABLE "public"."skills" ALTER COLUMN "user_id" TYPE bigint USING (user_id::bigint);
        ALTER TABLE "public"."skills" ALTER COLUMN "id" TYPE bigint USING (id::bigint);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'on_chain_transactions') THEN
        ALTER TABLE "public"."on_chain_transactions" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);
        ALTER TABLE "public"."on_chain_transactions" ALTER COLUMN "id" TYPE bigint USING (id::bigint);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'messages') THEN
        ALTER TABLE "public"."messages" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'interactions') THEN
        ALTER TABLE "public"."interactions" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);
        ALTER TABLE "public"."interactions" ALTER COLUMN "user_id" TYPE bigint USING (user_id::bigint);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'unlocks') THEN
        ALTER TABLE "public"."unlocks" ALTER COLUMN "conversation_id" TYPE bigint USING (conversation_id::bigint);
        ALTER TABLE "public"."unlocks" ALTER COLUMN "user_id" TYPE bigint USING (user_id::bigint);
    END IF;
END $$;

-- 5. Restore Foreign Key Constraints
ALTER TABLE "public"."conversations" ADD CONSTRAINT "conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "public"."conversation_skills" ADD CONSTRAINT "conversation_skills_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "public"."environments" ADD CONSTRAINT "environments_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'skills') THEN
        ALTER TABLE "public"."skills" ADD CONSTRAINT "skills_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'on_chain_transactions') THEN
        ALTER TABLE "public"."on_chain_transactions" ADD CONSTRAINT "on_chain_transactions_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'messages') THEN
        ALTER TABLE "public"."messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END $$;
